version: "3.8"
services:
  postgres:
    image: postgres:14.5
    container_name: biton-db
    command:
      - "postgres"
      - "-c"
      - "max_connections=${DB_MAX_CONNECTIONS:-64}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /opt/pg:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
