version: '3.8'

volumes:
    prometheus: {}
    grafana: {}

services:

  prometheus:
    image: ${REGISTRY}/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus:/prometheus
    restart: unless-stopped
    network_mode: host

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro,rslave
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--web.listen-address=localhost:9100'
    restart: unless-stopped
    network_mode: host

  grafana:
    image: ${REGISTRY}/grafana:latest
    container_name: grafana
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASS:-goodlife}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    network_mode: host
